[tool.tox]
legacy_tox_ini = """

[testenv]
skipsdist = true
skip_install = true

[base]
deps =
    pydantic[dotenv]<2.0
    requests
    srt

[testenv:cli]
setenv =
    ROOT_DIR = {toxinidir}
deps =
    {[base]deps}
commands =
    python -m srt_translator {posargs}

[testenv:opencc]
deps =
    opencc-python-reimplemented
commands =
    python -m opencc {posargs}

[testenv:check_format]
deps =
    black
commands =
    black {toxinidir} --check --diff --color {posargs}

[testenv:format]
deps =
    black
commands =
    black {toxinidir} {posargs}
"""

[tool.black]
line-length = 160
